### ISSUE TITLE
Meta Image does not load for link preview.

### ISSUE THREAD

**Issue by DesignrKnight** [getcovidhelpindia/react#2]
Have added meta image in the header but seems to have an issue
Done as per guide at metatags.io

**Comment by riteshsp2000** [comment]
Ill get onto this

**Comment by DesignrKnight** [comment]
![image](https://user-images.githubusercontent.com/27865704/117483509-6f6e2c80-af83-11eb-9ae0-19b7d18b6d35.png)

Seems to work now. Closing for now. Re-open if needed
